name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --workspace --verbose && cargo test --workspace --verbose -F unstable__deref
    - name: Verify MSRV
      run: cargo install cargo-msrv && cargo msrv verify --ignore-lockfile --verbose && cargo msrv verify --ignore-lockfile --verbose --features unstable__deref
    - name: Run examples
      run: cargo run -p foreign_crate --verbose
